[build-system]
requires = ["setuptools~=68.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "summary_pipeline"
description = "Summarises output from GPAS sub-workflows (part of WP8)."
dependencies = ["pandas ~=2.0"]
classifiers = [
    "Environment :: Console",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
]
requires-python = "~=3.11"
version = "2.5.0-rc1"

[project.scripts]
summary_json = "summary.summarise:cli_entry_point"

[project.optional-dependencies]
dev = [
    "pytest>=7.0",
    "pytest-mock",
    "pre-commit >= 3.2.2",
    "commitizen",
    "version_bumper @ git+https://github.com/GlobalPathogenAnalysisService/version_bumper.git",
]

[tool.commitizen]
name = "cz_conventional_commits"
update_changelog_on_bump = false
bump_message = "bump: version $current_version → $new_version" # [skip ci]"
version_type = "semver"
version_provider = "pep621"
tag_format = "$version"

[tool.version_bumper]
active_version = "2.5.0-rc1"
version_files = [
    "main.nf",
    ".github/workflows/manual_docker.yml",
]
