"""Command Line Interface"""
import argparse
from enum import Enum
import logging
from pathlib import Path
import sys

from summary.summarise import summarise


class ReportType(Enum):
    """Different types of report that can be generated by the pipeline.

    Args:
        Enum (_type_): Report type.
    """

    GATEKEEPER = "gatekeeper_report.json"
    MAPPING = "competitivemapping_report.json"
    MYKROBE = "mykrobe_report.json"
    GNOMONICUS = "gnomonicus.json"


class Arguments:  # pylint: disable=too-few-public-methods
    """Class for holding command line arguments."""

    def __init__(self, argv: list):
        """Initialise a command line argument object.

        Args:
            argv (list): A list of command line arguments, usually `sys.argv[1:]`.
        """
        parser = argparse.ArgumentParser(
            description="Process pipeline output to create a Summary JSON"
        )
        named_reports = parser.add_argument_group(title="Paths to individual reports")
        named_reports.add_argument(
            "--gatekeeper",
            dest="gatekeeper",
            help="Path to gatekeeper_report.json file",
        )
        named_reports.add_argument(
            "--mapping",
            dest="mapping",
            help="Path to competitivemapping_report.json file",
        )
        named_reports.add_argument(
            "--mykrobe", dest="mykrobe", help="Path to mykrobe_report.json file"
        )
        named_reports.add_argument(
            "--gnomonicus", dest="gnomonicus", help="Path to gnomonicus.json file"
        )
        report_list = parser.add_argument_group(title="Path to report list")
        report_list.add_argument(
            "--reports",
            nargs="+",
            dest="reports",
            help="A list of report files, the contents of which will be inferred by filename",
        )
        outputs = parser.add_argument_group(title="Output parameters")
        outputs.add_argument(
            "--output_path",
            default="Mega.json",
            dest="output",
            help="Path including name for output .json file",
        )
        args = parser.parse_args(argv)

        if args.reports:
            try:
                self.gatekeeper = self._get_report(args.reports, ReportType.GATEKEEPER)
            except ValueError as error:
                logging.info(error)
            try:
                self.mapping = self._get_report(args.reports, ReportType.MAPPING)
            except ValueError as error:
                logging.info(error)
            try:
                self.mykrobe = self._get_report(args.reports, ReportType.MYKROBE)
            except ValueError as error:
                logging.info(error)
            try:
                self.gnomonicus = self._get_report(args.reports, ReportType.GNOMONICUS)
            except ValueError as error:
                logging.info(error)
        else:
            self.gatekeeper = Path(args.gatekeeper)
            self.mapping = Path(args.mapping)
            self.mykrobe = Path(args.mykrobe)
            self.gnomonicus = Path(args.gnomonicus)
        self.output = Path(args.output)

    def _get_report(self, reports_list: list, report_type: ReportType) -> Path:
        """Get the path for a given report (e.g. from Gnomonicus).

        Args:
            reports_list (list): A list of Report objects.
            report_type (ReportType): The type of Report wanted.

        Raises:
            ValueError: Error raised when the type of report requested is not present.

        Returns:
            Path: Path of report.
        """
        for report in reports_list:
            if Path(report).name == report_type.value:
                return Path(report)
        raise ValueError(str(report_type) + " not found.")


def main():
    """CLI entry point."""
    logging.basicConfig(
        format="%(asctime)s — %(name)s — %(levelname)s — %(funcName)s:%(lineno)d — %(message)s",
        datefmt="%Y-%m-%dT%H:%M:%S%z",
        level=logging.DEBUG,
    )

    cli_args = Arguments(sys.argv[1:])

    summarise(cli_args)
