import argparse
import logging
from enum import Enum
from pathlib import Path


class ReportType(Enum):
    """Different types of report that can be generated by the pipeline.

    Args:
        Enum (_type_): Report type.
    """

    VERSIONS = "pipeline_versions.txt"
    KNOWLEDGE = "knowledge.json"
    GATEKEEPER = "speciation_report.json"
    MAPPING = "species_comparison_report.json"
    MYKROBE = "subspecies_report.json"
    CLOCKWORK = "genome_creation_report.json"
    GNOMONICUS = "resistance_prediction_report.json"
    NAME_MAPPING = "name_mapping.csv"


class Arguments:  # pylint: disable=too-few-public-methods
    """Class for holding command line arguments."""

    def __init__(self, argv: list):
        """Initialise a command line argument object.

        Args:
            argv (list): A list of command line arguments, usually `sys.argv[1:]`.
        """
        parser = argparse.ArgumentParser(
            description="Process pipeline output to create a Summary JSON"
        )
        named_reports = parser.add_argument_group(title="Paths to individual reports")
        named_reports.add_argument(
            "--versions",
            dest="versions",
            help="Path to pipeline_versions.txt file",
        )
        named_reports.add_argument(
            "--knowledge",
            dest="knowledge",
            help="Path to knowledge.json file",
        )
        named_reports.add_argument(
            "--gatekeeper",
            dest="gatekeeper",
            help="Path to speciation_report.json file",
        )
        named_reports.add_argument(
            "--mapping",
            dest="mapping",
            help="Path to species_comparison_report.json file",
        )
        named_reports.add_argument(
            "--mykrobe", dest="mykrobe", help="Path to subspecies_report.json file"
        )
        named_reports.add_argument(
            "--clockwork",
            dest="clockwork",
            help="Path to genome_creation_report.json file",
        )
        named_reports.add_argument(
            "--gnomonicus",
            dest="gnomonicus",
            help="Path to resistance_prediction_report.json file",
        )
        named_reports.add_argument(
            "--name_mapping",
            dest="name_mapping",
            help="Path to name_mapping.csv file",
        )
        report_list = parser.add_argument_group(title="Path to report list")
        report_list.add_argument(
            "--reports",
            nargs="+",
            dest="reports",
            help="A list of report files, the contents of which will be inferred by filename",
        )
        outputs = parser.add_argument_group(title="Output parameters")
        outputs.add_argument(
            "--output_path",
            default="Mega.json",
            dest="output",
            help="Path including name for output .json file",
        )
        args = parser.parse_args(argv)

        if args.reports:
            try:
                self.versions = self._get_report(args.reports, ReportType.VERSIONS)
            except ValueError as error:
                logging.info(error)
            try:
                self.knowledge = self._get_report(args.reports, ReportType.KNOWLEDGE)
            except ValueError as error:
                logging.info(error)
            # There must always be a gatekeeper report
            self.gatekeeper = self._get_report(args.reports, ReportType.GATEKEEPER)
            try:
                self.mapping = self._get_report(args.reports, ReportType.MAPPING)
            except ValueError as error:
                logging.info(error)
            try:
                self.mykrobe = self._get_report(args.reports, ReportType.MYKROBE)
            except ValueError as error:
                logging.info(error)
            try:
                self.clockwork = self._get_report(args.reports, ReportType.CLOCKWORK)
            except ValueError as error:
                logging.info(error)
            try:
                self.gnomonicus = self._get_report(args.reports, ReportType.GNOMONICUS)
            except ValueError as error:
                logging.info(error)
            self.name_mapping = self._get_report(args.reports, ReportType.NAME_MAPPING)
        else:
            self.versions = Path(args.versions)
            self.knowledge = Path(args.knowledge)
            self.gatekeeper = Path(args.gatekeeper)
            self.mapping = Path(args.mapping)
            self.mykrobe = Path(args.mykrobe)
            self.clockwork = Path(args.clockwork)
            self.gnomonicus = Path(args.gnomonicus)
            self.name_mapping = Path(args.name_mapping)
        self.output = Path(args.output)

    def _get_report(self, reports_list: list, report_type: ReportType) -> Path:
        """Get the path for a given report (e.g. from Gnomonicus).

        Args:
            reports_list (list): A list of Report objects.
            report_type (ReportType): The type of Report wanted.

        Raises:
            ValueError: Error raised when the type of report requested is not present.

        Returns:
            Path: Path of report.
        """
        for report in reports_list:
            if Path(report).name == report_type.value:
                return Path(report)
        raise ValueError(str(report_type) + " not found.")
