"""Reports"""
from enum import Enum
import json
from pathlib import Path


class ReportType(Enum):
    """Different types of report that can be generated by the pipeline.

    Args:
        Enum (_type_): Report type.
    """

    GATEKEEPER = "gatekeeper_report.json"
    MAPPING = "competitivemapping_report.json"
    MYKROBE = "mykrobe_report.json"
    GNOMONICUS = "gnomonicus.json"


class Report:  # pylint: disable=too-few-public-methods
    """Holds information about a report including its type, path and contents."""

    def __init__(self, report_type: ReportType, report_path: Path) -> None:
        self.report_type = report_type
        self.report_path = report_path
        with open(self.report_path, "r") as file:
            self.report_contents = json.load(file)


class ReportList(list):
    """A list of reports."""

    def retrieve(self, report_type: ReportType) -> Report:
        """Retrieve a report of a particular type.

        Args:
            report_type (ReportType): Report type.

        Raises:
            ValueError: Raised if the requested type of report is not present.

        Returns:
            Report: Object representing the requested report.
        """
        for report in self:
            if report.report_type == report_type:
                return report
        raise ValueError(str(report_type) + " not in collection.")

    def contains(self, report_type: ReportType) -> bool:
        """Checks if a particular type of report is present.

        Args:
            report_type (ReportType): Report type.

        Returns:
            bool: Is the report present?
        """
        found = False
        for report in self:
            if report.report_type == report_type:
                found = True

        return found

    def __str__(self) -> str:
        """String

        Returns:
            str: A human readable string representation of the list of report.
        """
        report_strings = []
        for report in self:
            report_strings.append(report.report_path)
        return str(report_strings)
