name: Tests (pytest)

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - main
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 0 * * 0' # Every Sunday at midnight

jobs:
  build:
    name: Ex1 (${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install pytest 
      - name: Test with pytest
        run: |
          pytest