name: Tests (pytest)

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Ex1 (${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v4
        with:
          token: "${{ secrets.PAT_TOKEN }}"
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install .[dev]
      - name: Validate commits
        if: github.ref != 'refs/heads/main'
        run: |
          cz check --rev-range origin/main..
      - name: Test with pytest
        run: |
          pytest
  nf-test:
    runs-on: ubuntu-latest
    steps:
      - name: Build docker container
        run: |
          docker build -t summary_test .
      - name: Inspect
        run: |
          docker image inspect summary_test

      - name: Run nf-test
        run: nf-test test tests/workflow.nf.test --profile local_docker