name: "Bump version"

on:
  push:
    branches:
      - main

jobs:

  bump-version:
    name: "Bump version with Commitizen"
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.cz.outputs.version }}
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.VERSION_BUMP_TOKEN }}

      - name: Install Commitizen
        run: |
          python3 -m pip install commitizen

      - name: Validate commits
        if: github.ref != 'refs/heads/main'
        run: |
          cz check --rev-range origin/main..

      # - name: Update changelog
      #   if: github.ref == 'refs/heads/main'
      #   run: echo "changelog=-ch " >>"${GITHUB_ENV}"
      #
      - id: cz
        if: github.ref == 'refs/heads/main'
        name: Bump version
        run: |
          git config --local user.name 'github-actions[bot]'
          git config --local user.email 'github-actions[bot]@users.noreply.github.com'

          cz bump --version-type semver --check-consistency # ${changelog}

          echo "version=$(cz version --project)" >> ${GITHUB_OUTPUT}

      - name: Push commit
        if: github.ref == 'refs/heads/main'
        run: |
          git push
          git push --tags

      - name: Print version
        if: github.ref == 'refs/heads/main'
        run: echo "Bumped to version ${{ steps.cz.outputs.version }}"
